// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "SSID"
#define SECRET_PASS "PASS"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "BROKER"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIIChjCCAW6gAwIBAgIUDacnuSV9AvNHR7+qXcV1uSElu3kwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIwMTEyOTIyMjM0
NFoXDTQ5MTIzMTIzNTk1OVowFjEUMBIGA1UEAxMLTUtSV2lGaTEwMTAwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAATlnNq9AboLNqbAXNSij1QsmCuYjg3vYALkD3i3
54KK1pfr/kYsgX8+kuqV5jfJLBiEMtWXSx54gljs8jbSBHmfo2AwXjAfBgNVHSME
GDAWgBSJcMrV4QM3vVZfnSHkGHzWuPCWjzAdBgNVHQ4EFgQU/2n1BuXlW/CKPQPx
QwHroZV9joYwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcN
AQELBQADggEBAJkxL6VpLxjCiUX5ln+Oe2rsFhAKgHdX5Euw4Uwu4DGgmVegIcHg
1VrlWg+paU4s8tWRXO/JjlLByQ2WdtQUEc1dxyFT2nst0mFtm41ipvxw6cPA33ti
vXUOpaED9VogNH93jKpI4PyTiGPTVKdCK29ap+jZ3p0PXqwg+NGMbXO6foJk6aUi
V0ncovLXrfFynbWm2JxojoNrRl8D5oaEteQyUSLQlByn1VcDPQo+AefFk6tH+pNy
7UfZ4sjhlAS2fXsQzx7XYRn0GfCuvX2vDUYKiCgHWRBsBfmhS3WBOVnDVH2GDGV9
cfdrjdjw/6Sc8vtCLg4Jaho8vEBx0mL5abU=
-----END CERTIFICATE-----
)";
